Fix MissingPropertyException for buildCauses
Sometimes for some builds there seems to be a different implementation
of RunWrapper being used by Jenkins, which does not have a buildCauses
property.

Resulting error message is

    groovy.lang.MissingPropertyException: No such property: buildCauses for class: org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper

Signed-off-by: Michael Kutz <michael.kutz@rewe-digital.com>